import React from 'react'
import Firstnav from '../layout/firstnav'
import './courses.css'

export default function Graphics() {
  return (
    <div>
        <Firstnav/>
      <div className='graphicdiv ms-5 mt-5'>
      <h1 className='graphicheader ms-2 mt-4'>Graphics:</h1>
      <h6 className='coursesheadersix ms-5 mt-3'>Graphics (from Ancient Greek γραφικός (graphikós) 'pertaining to drawing, painting, writing, etc.') are visual images or designs on some surface, such as a wall, canvas, screen, paper, or stone, to inform, illustrate, or entertain. In contemporary usage, it includes a pictorial representation of data, as in design and manufacture, in typesetting and the graphic arts, and in educational and recreational software. Images that are generated by a computer are called computer graphics.

Examples are photographs, drawings, line art, mathematical graphs, line graphs, charts, diagrams, typography, numbers, symbols, geometric designs, maps, engineering drawings, or other images. Graphics often combine text, illustration, and color. Graphic design may consist of the deliberate selection, creation, or arrangement of typography alone, as in a brochure, flyer, poster, web site, or book without any other element. The objective can be clarity or effective communication, association with other cultural elements, or merely the creation of a distinctive style.

Graphics can be functional or artistic. The latter can be a recorded version, such as a photograph, or interpretation by a scientist to highlight essential features, or an artist, in which case the distinction with imaginary graphics may become blurred. It can also be used for architecture.</h6>
<div className='graphicimg mt-3'></div>
      </div>
    </div>
  )
}
